### ISSUE TITLE
Singapore facts uses ExactStrMatch can reduces accuracy 

### ISSUE THREAD

**Issue by tsailiming** [aiverify-foundation/moonshot-data#64]
Not all LLM models will return the answer to match the target exactly thus will likely fail the `ExactStrMatch` metric comparison. 

Are there alternatives that can fit the purpose?

**Comment by miyamaya9** [comment]
Hi @tsailiming Apologies for the delayed in response. Regarding your question, perhaps you might want to consider alternatives like RelaxedStrMatch and semantic similarity metrics can offer more flexible evaluations, which could focusing on the accuracy of the conveyed information rather than exact wording.
